# Deployment configuration for create_deployment.sh
PublicBucket=
PrivateBucket=
KeyPairName=
EmailAddress=
DeployBucketRegion=us-east-1
DBDeployPackage=db.tar.gz
PASOEDeployPackage=pas.tar.gz
WebDeployPackage=web.tar.gz
AvailabilityZones=us-east-1a,us-east-1b
